User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10

# Filter settings for Allowlist (Default Deny)
Allow 127.0.0.1
Allow ::1

Filter "/etc/tinyproxy/allowlist.txt"
FilterType fnmatch
FilterCaseSensitive Off
FilterDefaultDeny Yes
